---

# cover all files (even if a file isn't touched by any test)
all: true

# check coverage percentage and fail test if below threshold
check-coverage: true

# thresholds
branches: 60
lines: 60
functions: 60
statements: 60
